- build/home.css
- src/pages/home/index.scss
Set the home page title to center
Signed-off-by: leilei.gll <leilei.gll@alibaba-inc.com>
> Set the home page title to center

- build/home.css
- src/pages/home/index.scss
Resize the image
Signed-off-by: leilei.gll <leilei.gll@alibaba-inc.com>
> Resize the image

- docs/en-us/developers/contributor-guide/new-contributor-guide_dev.md
- docs/zh-cn/developers/contributor-guide/new-contributor-guide_dev.md
Signed-off-by: slievrly <slievrly@163.com>
> optimize: fix docs link url

- robots.txt
Signed-off-by: slievrly <slievrly@163.com>
> optimize: update sitemap url

- docs/en-us/user/quickstart.md
- docs/zh-cn/user/quickstart.md
Shall I commit the build results as well?
> Translate quick-start documentation to English.

- docs/en-us/user/wasm-go.md
- docs/zh-cn/user/wasm-go.md
https://github.com/alibaba/higress/issues/70
> Translate wasm-go documentation to English.

- .github/workflows/deploy-oss.yml
- .github/workflows/deploy.yml
Signed-off-by: slievrly <slievrly@163.com>
> optimize: deploy to OSS every 12 hours

- docs/en-us/ops/deploy-by-helm.md
- docs/zh-cn/ops/deploy-by-helm.md
https://github.com/alibaba/higress/issues/69
> Translate deploy-by-helm document to English.

- docs/en-us/user/quickstart.md
- docs/zh-cn/user/quickstart.md
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> docs: update higress version

- docs/en-us/developers/contributor-guide/new-contributor-guide_dev.md
- docs/en-us/developers/guide_dev.md
- docs/zh-cn/developers/contributor-guide/new-contributor-guide_dev.md
- docs/zh-cn/developers/guide_dev.md
Fix incorrect branch names and links in guide_dev page.
> Fix incorrect branch names and links in guide_dev page.

- docs/en-us/developers/developers_dev.md
- docs/zh-cn/developers/developers_dev.md
Signed-off-by: bitliu <bitliu@tencent.com>
> docs: update developers_dev.md

- site_config/home.jsx
- src/pages/home/index.jsx
- template.ejs
Signed-off-by: slievrly <slievrly@163.com>
> optimize: support for an English version of the microservices landscape

- docs/en-us/ops/deploy-by-helm.md
- docs/en-us/user/quickstart.md
- docs/zh-cn/ops/deploy-by-helm.md
- docs/zh-cn/ops/upgrade.md
- docs/zh-cn/user/quickstart.md
Use helm repo instead of OCI image as the installation source
> doc: Use helm repo instead of OCI image as the installation source

- CODEOWNERS
- docs/en-us/ops/deploy-by-helm.md
- docs/zh-cn/dev/architecture.md
Remove the instructions of how to build Higress Istio.
> doc: Remove the instructions of how to build Higress Istio

- docs/dev/architecture.md
- docs/developers/developers_dev.md
- docs/ops/deploy-by-helm.md
- docs/ops/upgrade.md
- docs/user/quickstart.md
- docusaurus.config.js
- i18n/en-us/code.json
- i18n/en-us/docusaurus-plugin-content-docs/current/developers/developers_dev.md
- i18n/en-us/docusaurus-plugin-content-docs/current/ops/deploy-by-helm.md
- i18n/en-us/docusaurus-plugin-content-docs/current/user/quickstart.md
- i18n/zh-cn/code.json
- i18n/zh-cn/docusaurus-plugin-content-docs/current/dev/architecture.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/developers/developers_dev.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/ops/deploy-by-helm.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/ops/upgrade.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/quickstart.md
- src/pages/home/feature/index.tsx
- src/pages/index.tsx
fix: fix some bug and pick commit from master
> fix: fix some bug and pick commit from master

- docs/en-us/user/wasm-go.md
- docs/zh-cn/user/wasm-go.md
feat: doc for building wasm-go
> feat: doc for building wasm-go

- docs/user/dubbo-envoyfilter.md
- i18n/en-us/docusaurus-plugin-content-docs/current/user/dubbo-envoyfilter.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/dubbo-envoyfilter.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/dubbo.md
- sidebars.js
> Add HTTP to Dubbo docs

- i18n/en-us/docusaurus-plugin-content-docs/current/user/quickstart.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/quickstart.md
doc: Update local deployment section of the quick-start guide
> doc: Update local deployment section of the quick-start guide

- i18n/en-us/docusaurus-plugin-content-docs/current/user/prometheus.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/prometheus.md
Add the English version of Prometheus integration guide
> doc: Add the English version of Prometheus integration guide

- i18n/en-us/docusaurus-plugin-content-docs/current/dev/code.md
- i18n/en-us/docusaurus-plugin-content-docs/current/developers/committer-guide/label-an-issue-guide_dev.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/plugins/basic-auth.md
> fix docs typos

- i18n/en-us/code.json
- i18n/zh-cn/code.json
- src/pages/home/community/index.tsx
Update the title of community section of homepage
> fix: Update the title of community section of homepage

- i18n/en-us/docusaurus-plugin-content-docs/current/dev/architecture.md
- i18n/en-us/docusaurus-plugin-content-docs/current/ops/deploy-by-helm.md
- i18n/en-us/docusaurus-plugin-content-docs/current/user/quickstart.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/ops/deploy-by-helm.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/quickstart.md
1. Add helm chart parameter list into deploy-by-helm document 
1. Fix incorrect TOC levels of quickstart document
2. Fix the inconsistent title casing in the architecture document
fixes https://github.com/alibaba/higress/issues/251 https://github.com/alibaba/higress/issues/295
> doc: Add helm chart parameter list into deploy-by-helm document with some other changes

- docs/user/wasm-image-spec.md
- i18n/en-us/docusaurus-plugin-content-docs/current/user/wasm-image-spec.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/wasm-image-spec.md
- sidebars.js
Add document of Wasm Plugin Image Specification
> doc: Add document of Wasm Plugin Image Specification

- i18n/en-us/docusaurus-plugin-content-docs/current/developers/developers_dev.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/developers/developers_dev.md
Apply new one Committer for Hinsteny.
> Apply new one Committer

- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/annotation.md
fix item `nginx.ingress.kubernetes.io/session-cookie-path`.
> docs: update annotation.md

- docs/user/configmap.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/configmap.md
- sidebars.js
> add configmap doc

- src/pages/home/top/index.tsx
Update version displayed on homepage to 1.1.0
> rel: Update version to 1.1.0

- blog/config-with-file.md
- docs/ops/deploy-by-docker-compose.md
- i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
- i18n/en-us/docusaurus-plugin-content-docs/current.json
- i18n/en-us/docusaurus-plugin-content-docs/current/ops/deploy-by-docker-compose.md
- i18n/en-us/docusaurus-plugin-content-docs/current/ops/deploy-by-helm.md
- i18n/zh-cn/docusaurus-plugin-content-blog/config-with-file.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current.json
- i18n/zh-cn/docusaurus-plugin-content-docs/current/ops/deploy-by-docker-compose.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/ops/deploy-by-helm.md
- sidebars.js
Note: Do not merge this one before https://github.com/higress-group/higress-standalone/pull/29
----------
----------
> docs: Add a blog and user manual for standalone deployment

- src/pages/home/top/index.tsx
> rel: Update the latest version to 1.2.0

- i18n/zh-cn/docusaurus-plugin-content-docs/current/ops/deploy-by-docker-compose.md
Fix following display issues:
https://higress.io/zh-cn/docs/ops/deploy-by-docker-compose/
> fix: Fix some incorrect styles in deploy-by-docker-compose page

- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/wasm-go.md
Update wasm-go.md 可能在windows中出现的一些编译问题
> Update wasm-go.md 可能在windows中出现的一些编译问题

- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/dubbo-http2rpc.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/dubbo.md
http2rpc supports treating the entire body as a method parameter
> http2rpc support paramFromEntireBody

- docusaurus.config.js
- package-lock.json
- package.json
> feat: Upgrade docusaurus and install docusaurus-plugin-image-zoom plugin

- i18n/en-us/docusaurus-plugin-content-docs/current/dev/architecture.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/dev/architecture.md
> doc: Add more detailed description regarding how to build an image of Higress Gateway

- i18n/zh-cn/docusaurus-plugin-content-docs/current/plugins/intro.md
> Spelling Mistake Fix

- i18n/en-us/docusaurus-plugin-content-docs/current/user/wasm-go.md
- i18n/en-us/docusaurus-plugin-content-docs/current/user/wasm-image-spec.md
- i18n/zh-cn/docusaurus-plugin-content-blog/30-line-wasm.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/wasm-image-spec.md
fix https://github.com/alibaba/higress/issues/1100
> fix: Fix incorrect Wasm plugin build commands

- i18n/zh-cn/docusaurus-plugin-content-docs/current/plugins/ai/ai-proxy.md
https://github.com/alibaba/higress/pull/1068#issuecomment-2212476221
> doc: update ai-proxy doc

- src/components/cloud/FunctionalCompare/Tableplugin.jsx
- src/constant.ts
> feat:修改功能对比内容

- src/components/home/HomeIntroduce.astro
There is a problem with the adaptation of the title animation effect. Please restore it to its original state first, and then resubmit it when it is adapted.
> [Revert]There is a problem with the adaptation of the title animation effect.

- src/content/docs/latest/zh-cn/dev/architecture.md
> 针对编译和本地开发添加一些新手tips

- .gitignore
- src/content/docs/latest/_sidebar.json
- src/content/docs/latest/en/ops/how-tos/https-upstream.md
> feat: Add how-tos into the sidebar

- src/content/docs/ebook/en/wasm14.md
- src/content/docs/ebook/en/wasm15.md
- src/content/docs/ebook/en/wasm18.md
- src/content/docs/ebook/zh-cn/wasm14.md
- src/content/docs/ebook/zh-cn/wasm15.md
- src/content/docs/ebook/zh-cn/wasm18.md
- src/content/docs/latest/zh-cn/user/wasm-go.md
Update "envoy.filters.http.router" configuration in envoy.yaml files.
See: https://github.com/envoyproxy/envoy/issues/21464
> fix: Update "envoy.filters.http.router" configuration in envoy.yaml files

- src/components/home/HomeIntroduce.astro
Update the latest release version to 2.0.1.
> feat: Update the latest release version to 2.0.1

- src/content/docs/latest/zh-cn/plugins/ai/api-consumer/ai-quota.md
fix typos in ai-quota document
> fix: typos in ai-quota

- i18n/zh-cn/docusaurus-plugin-content-docs/current/user/configmap.md
feature: add route timeout info on global configmap
related mr: https://github.com/alibaba/higress/pull/883
> Feature add route timeout info on global configmap

- src/content/docs/latest/zh-cn/user/configmap.md
I think the following description maybe incorrect. If yes, please merge this pr, if not, please ingore it. thanks
> docs:correct higress-https config

- src/content/ai/mcp-quick-start.md
> docs: add mcp-quick-start.md

- src/content/ai/en/mcp-quick-start.md
- src/content/ai/mcp-quick-start.md
> add nacos mcp regitry notes

- src/content/docs/developers/zh-cn/developers_dev.md
https://github.com/alibaba/higress/pull/1922
https://github.com/alibaba/higress/pull/1983
https://github.com/alibaba/higress/pull/2002
https://github.com/higress-group/higress-group.github.io/pull/390
https://github.com/alibaba/higress/issues/1434
> docs: add contributor

- src/content/ai/en/mcp-quick-start.md
- src/content/ai/mcp-quick-start.md
fix nacos registry config fotmat
> fix nacos registry config fotmat

- src/content/ai/en/mcp-quick-start.md
- src/content/ai/mcp-quick-start.md
> Update nacos mcp regsitry doc

- src/content/ai/en/mcp-quick-start.md
- src/content/ai/mcp-quick-start.md
Fix mcp registry endpoint description
> Fix mcp registry endpoint description

- src/content/ai/en/mcp-quick-start.md
- src/content/ai/mcp-quick-start.md
Revert last 2 revert and remove mcp server config in nacos mcp registry doc
> Update nacos registry doc

- src/content/docs/developers/en/developers_dev.md
- src/content/docs/developers/zh-cn/developers_dev.md
- https://github.com/alibaba/higress/pull/1617
- https://github.com/alibaba/higress/pull/2319
- https://github.com/higress-group/mock-server/pull/1
- https://github.com/higress-group/mock-server/pull/5
- https://github.com/higress-group/higress-console/pull/472
- https://github.com/higress-group/higress-console/pull/429
> [Member Apply] wuwenqi

- src/content/ai/mcp-quick-start.md
此前 mcp-quick-start 文档仍是使用插件&命令行方式操作，现修改为UI方式。
> 优化 mcp-quick-start

- src/i18n/en/ui.ts
- src/i18n/zh-cn/ui.ts
- 将“易用性”修改为“微服务和 API 管理”以更准确表达内容
- 维护其他功能比较章节的翻译一致性
- 优化中文版界面文本的专业性和明确性
> feat(i18n): 更新功能比较章节的可用性描述
