Dockerfile
Dockerfile-Base
README.md

Since the way of local deploy is difficult for most users, we provide the way of docker deploy to help users to contribute the higress docsite together.
Fix https://github.com/higress-group/higress-group.github.io/issues/27.

Support docker deploy

---

docs/zh-cn/user/quickstart.md

```
helm install istio -n istio-system oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/charts/istio
Pulled: higress-registry.cn-hangzhou.cr.aliyuncs.com/charts/istio:1.12.2
Digest: sha256:8768284b6cf30c93a656fafcbac1805d1420c725beb6e118f70de9d19c95d53b
Error: INSTALLATION FAILED: create: failed to create: namespaces "istio-system" not found
```

bugfix: quickstart namespaces not found

---

i18n/en-us/docusaurus-plugin-content-docs/current/plugins/jwt-auth.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/plugins/jwt-auth.md

fix typo from `ture` to `true`

fix typo from `ture` to `true`

---

i18n/en-us/docusaurus-plugin-content-docs/current/dev/architecture.md

translate [组间编译说明](https://higress.io/zh-cn/docs/dev/architecture) in official web to English.

add en-us page about component compilation instructions

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/user/annotation-use-case.md

Correct a word spelling error
[alibaba/higress](https://github.com/alibaba/higress)
pkg\ingress\kube\annotations\canary.go Line 28 
Confirm the correct spelling of this annotation
```go
const (
enableCanary          = "canary"
canaryByHeader        = "canary-by-header"
canaryByHeaderValue   = "canary-by-header-value"
canaryByHeaderPattern = "canary-by-header-pattern"
canaryByCookie        = "canary-by-cookie"
canaryWeight          = "canary-weight"
canaryWeightTotal     = "canary-weight-total"
defaultCanaryWeightTotal = 100
)
```
已在 [higress 主项目](https://github.com/alibaba/higress)
pkg\ingress\kube\annotations\canary.go 28行 确认此注解的正确拼写

fix: Update annotation-use-case.md

---

i18n/en-us/docusaurus-plugin-content-docs/current/dev/code.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/dev/code.md

`diff -Naur external/envoy external/envoy_new > envoy/1.20/patches/envoy/$(date +%Y%m%d)-what-changed.patch`
The patch file produced by this command cannot be pathed to source code.

fix code-reading guide

---

.gitignore
README.md
docs/plugins/ai-proxy.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/plugins/ai-proxy.md
sidebars.js

内容来自 ai-proxy 插件的 [README 文档](https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-proxy/README.md), 在此基础上补充了 groq, claude 插件的文档，并在最后添加了完整的配置示例。
groq PR: https://github.com/alibaba/higress/pull/967
claude PR: https://github.com/alibaba/higress/pull/969

doc: add ai-proxy plugin

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/plugins/traffic/cluster-key-rate-limit.md

- 将 `key-cluster-rate-limit` 改为 `cluster-key-rate-limit`.
- 在文档中说明 cluster-key-rate-limit 与 key-rate-limit 插件的区别。

doc: update cluster-key-rate-limit doc

---

src/components/home/HomeIntroduce.astro

On iOS devices, Safari handles videos differently compared to desktop browsers. Safari on iOS, to conserve battery and optimize performance, does not allow videos to autoplay, play muted, or play in the background by default. In some cases, the video may also overlay other elements.
To address this, media queries can be used to adapt the content based on the device type. For instance, by detecting the screen size or platform, you can choose to hide the video on smaller screens (like those of mobile devices) and display a static image or other alternative content instead. This ensures that the website functions smoothly across all devices and avoids issues like videos covering important content.
Here’s how media queries can be applied:
1. Use a media query to detect when the screen width …

[Fix] Use media queries to address video issues on iOS devices and optimize performance for website loading

---

src/components/home/HomeIntroduce.astro

```html
<script>
// Execute the callback function when the DOM content is fully loaded and parsed
document.addEventListener('DOMContentLoaded', () => {
// Define a function to update media content (video or image)
function updateMedia() {
// Get the element with class 'media-container'
const mediaContainer = document.querySelector('.media-container');
// Check the current window width
if (window.innerWidth <= 768) {
// If the window width is less than or equal to 768 pixels (typically mobile devices), insert an image
mediaContainer.innerHTML = `
<div id="background-image" class="image-background" 
style="background-image: url('https://img.alicdn.com/imgextra/i1/O1CN01U3PG171Wiz4B85TGK_!!6000000002823-0-tps-2388-1168.jpg');"></div>
`;
} else {
// If the window width is greater than 768 …
```

Performance optimization：JavaScript Performance Optimization for Mobile Adaptation to Improve Page Responsiveness

---

src/content/docs/developers/zh-cn/developers_dev.md

I noticed some display issues in the documentation, so I've adjusted the Markdown format accordingly.

correct the Markdown format in the documentation. 

---

src/content/docs/latest/en/user/wasm-image-spec.md
src/content/docs/latest/zh-cn/user/wasm-image-spec.md

According to OpenAPI extensions documentation, custom fields need use names started with "x-".
https://swagger.io/docs/specification/v3_0/openapi-extensions/

fix: Use x-scope instead of scope as field name in Wasm spec

---

src/components/common/Header/searchComp/index.astro

1. Use the current domain instead of the official domain "higress.io".
2. Exclude search results with an incorrect locale.

feat: Improve search function

---

src/content/docs/latest/en/ops/deploy-by-helm.md
src/content/docs/latest/zh-cn/ops/deploy-by-helm.md
src/content/docs/latest/zh-cn/user/configurations.md

在低版本内核不便于配置权限的情况下，用户也可以通过修改监听端口来绕过非root不得监听小于1024的端口的问题。

feat: Add gateway ports properties to helm values documents

---

.gitignore
src/content/docs/latest/en/ops/deploy-by-aliyun-computenest.md
src/content/docs/latest/zh-cn/ops/deploy-by-aliyun-computenest.md

图片显示异常，GitHub 仓库中的图片链接应使用以 raw.githubusercontent.com 开头的链接。

fix: aliyun computenest image links

---

src/content/blog/configmap.md
src/content/blog/higress-code.md
src/content/blog/skywalking.md
src/content/docs/ebook/en/wasm14.md
src/content/docs/ebook/en/wasm15.md
src/content/docs/ebook/en/wasm16.md
src/content/docs/ebook/en/wasm17.md
src/content/docs/ebook/en/wasm18.md
src/content/docs/ebook/en/wasm19.md
src/content/docs/ebook/zh-cn/wasm14.md
src/content/docs/ebook/zh-cn/wasm15.md
src/content/docs/ebook/zh-cn/wasm16.md
src/content/docs/ebook/zh-cn/wasm17.md
src/content/docs/ebook/zh-cn/wasm18.md
src/content/docs/ebook/zh-cn/wasm19.md
tailwind.config.mjs

1. Use monospaced fonts.
2. Fix incorrect code language names.
https://higress.cn/blog/skywalking/?spm=36971b57.2ef5001f.0.0.2a932c1fEHuPti&source=blog

fix: Fix incorrect code section display styles

---

src/content/docs/latest/en/plugins/ai/others/ai-intent.md
src/content/docs/latest/zh-cn/plugins/ai/others/ai-intent.md

docs: escape '|' in markdown table 

---

src/content/docs/latest/en/plugins/ai/api-consumer/ai-token-ratelimit.md
src/content/docs/latest/zh-cn/plugins/ai/api-consumer/ai-token-ratelimit.md

Currently, ai-token-ratelimit does not rely on ai-statistics plugin, remove ai-statistics from the documentation.
fixes: https://github.com/alibaba/higress/issues/1760

feat: update ai-token-ratelimit documentation by removing ai-statistics plugin

---

src/content/docs/latest/en/plugins/authentication/ext-auth.md
src/content/docs/latest/en/plugins/security/replay-protection.md
src/content/docs/latest/zh-cn/plugins/authentication/ext-auth.md
src/content/docs/latest/zh-cn/plugins/security/replay-protection.md

sync ext-auth and replay-protection docs

doc: Sync ext-auth and replay-protection docs

---

src/components/starlight/Head.astro

- 移除了 beacon-aplus 脚本中的 exparams 属性
- 减少了 aes 跟踪器插件的加载数量，仅保留 tracker 和 tracker-plugin-pv
- 删除了多个不必要的 AES 插件初始化代码

refactor(components): 简化 Head 组件中的脚本加载逻辑
